# Check out code, set up Java, create, stage and publish site with Maven.

name: maven-site-deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  site-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 📥 Check out code
      uses: actions/checkout@v3

    - name: ☕ Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'

    - name: 📑 Create site with Maven
      run: mvn site

    - name: 📤 Publish site to gh-pages
      run: mvn scm-publish:publish-scm
